//
// Created by p0w3r on 13.03.16.
//

#ifndef CARDRECOGNITIONSYSTEM_CARDDETECTORSTAGE_H
#define CARDRECOGNITIONSYSTEM_CARDDETECTORSTAGE_H


class CardDetectorStage {

};


#endif //CARDRECOGNITIONSYSTEM_CARDDETECTORSTAGE_H
