//
// Created by p0w3r on 13.03.16.
//

#ifndef CARDRECOGNITIONSYSTEM_CARDREPOSITORYCONTROLLER_H
#define CARDRECOGNITIONSYSTEM_CARDREPOSITORYCONTROLLER_H


class CardRepositoryController {

};


#endif //CARDRECOGNITIONSYSTEM_CARDREPOSITORYCONTROLLER_H
