//
// Created by p0w3r on 20.03.16.
//

#ifndef CARDRECOGNITIONSYSTEM_CRS_PIPELINEWORKLOAD_H
#define CARDRECOGNITIONSYSTEM_CRS_PIPELINEWORKLOAD_H


class CRS_PipelineWorkload {

};


#endif //CARDRECOGNITIONSYSTEM_CRS_PIPELINEWORKLOAD_H
