//
// Created by p0w3r on 20.03.16.
//

#ifndef CARDRECOGNITIONSYSTEM_CRS_PIPELINEBUFFER_H
#define CARDRECOGNITIONSYSTEM_CRS_PIPELINEBUFFER_H


class CRS_PipelineBuffer {

};


#endif //CARDRECOGNITIONSYSTEM_CRS_PIPELINEBUFFER_H
