//
// Created by p0w3r on 20.03.16.
//

#ifndef CARDRECOGNITIONSYSTEM_CRS_PIPELINELOAD_H
#define CARDRECOGNITIONSYSTEM_CRS_PIPELINELOAD_H


class CRS_PipelineLoad {

};


#endif //CARDRECOGNITIONSYSTEM_CRS_PIPELINELOAD_H
